# terraformはバージョンによって書き方が異なるみたいなので、固定した方が無難だと思われ
# FROM hashicorp/terraform:latest
FROM hashicorp/terraform:1.3.1

# 作業ディレクトリ設定
WORKDIR /tmp/terraform

# コンテナを起動し続ける
ENTRYPOINT ["/bin/sh", "-c", "while :; do sleep 10; done"]
